
[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "0.0.6"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
python = "2.7.*"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "31404cdc49dbe26754b19c01292c520ae14a1781c6e1780cb0ffe9d3e69aed77"
source = "https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz"
source_sha256 = "18617d1f15a380a919d517630a9cd85ce17ea602f9bbdc58ddc672df4b0239db"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.15-linux-x64-cflinuxfs3-31404cdc.tgz"
version = "2.7.15"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "57e6940767c4c2b4c6433e382c166c4947c1f1e259c5b9e93bf196316a4e4e2f"
source = "https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz"
source_sha256 = "01da813a3600876f03f46db11cc5c408175e99f03af2ba942ef324389a83bad5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.16-linux-x64-cflinuxfs2-57e69407.tgz"
version = "2.7.16"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "978c1153db5f6d4c351463fdb4db6ed7be7dc3f3aca13551f2daa7c65414b26e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.16-linux-x64-cflinuxfs2-978c1153.tgz"
version = "2.7.16"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "cb0dd1e4e4c7a37fb7397774edb75b67ea9532e0b93b31f0b10bf11f666081b6"
source = "https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz"
source_sha256 = "01da813a3600876f03f46db11cc5c408175e99f03af2ba942ef324389a83bad5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.16-linux-x64-cflinuxfs3-cb0dd1e4.tgz"
version = "2.7.16"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "cefa2b44d2b4ce351bc4e19769b17911cd5198729e58d48465790d677999cb21"
source = "https://www.python.org/ftp/python/3.4.9/Python-3.4.9.tgz"
source_sha256 = "e02e565372750a6678efe35ddecbe5ccd5330a8a2e8bbe38d3060713492e3dab"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.9-linux-x64-cflinuxfs3-cefa2b44.tgz"
version = "3.4.9"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "c205db1fd96fd9fb951d449fc4f7a9db6a94c5bfa6d3324c512f50fb7e3dd06e"
source = "https://www.python.org/ftp/python/3.4.10/Python-3.4.10.tgz"
source_sha256 = "217757699249ab432571b381386d441e12b433100ab5f908051fcb7cced2539d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.10-linux-x64-cflinuxfs2-c205db1f.tgz"
version = "3.4.10"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "14ccdc196c4bd99f781d942be814122592c7ed81909c4015381c758d0399d716"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.10-linux-x64-cflinuxfs2-14ccdc19.tgz"
version = "3.4.10"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "987b05af82915e0de48498b10295d740aa3f4eec5d01d3457ac1cc357f06b31c"
source = "https://www.python.org/ftp/python/3.4.10/Python-3.4.10.tgz"
source_sha256 = "217757699249ab432571b381386d441e12b433100ab5f908051fcb7cced2539d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.10-linux-x64-cflinuxfs3-987b05af.tgz"
version = "3.4.10"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "c9eedd806db6ead7039cdc1e4bcada8ef295c95d329b191c03ddf3deb604df7e"
source = "https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz"
source_sha256 = "30d2ff093988e74283e1abfee823292c6b59590796b9827e95ba4940b27d26f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.6-linux-x64-cflinuxfs3-c9eedd80.tgz"
version = "3.5.6"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "b17939ee9bcb8538baf4642d561c35754cba822b9672cde531c430a320995669"
source = "https://www.python.org/ftp/python/3.5.7/Python-3.5.7.tgz"
source_sha256 = "542d94920a2a06a471a73b51614805ad65366af98145b0369bc374cf248b521b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.7-linux-x64-cflinuxfs2-b17939ee.tgz"
version = "3.5.7"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "8260b09fad168683694e6ef4f7d126c83730b606f8af835e46f83b9665416f1d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.7-linux-x64-cflinuxfs2-8260b09f.tgz"
version = "3.5.7"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "66c1605d7a4819ff66588d9d984a014a1cf53526b9bae642040ecb2eaf655e5a"
source = "https://www.python.org/ftp/python/3.5.7/Python-3.5.7.tgz"
source_sha256 = "542d94920a2a06a471a73b51614805ad65366af98145b0369bc374cf248b521b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.7-linux-x64-cflinuxfs3-66c1605d.tgz"
version = "3.5.7"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "70a1f47b1d7eccd0068cc1670ee3b29f92d02f847308ceb0e9027a3e4f8a7b94"
source = "https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz"
source_sha256 = "b7c36f7ed8f7143b2c46153b7332db2227669f583ea0cce753facf549d1a4239"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.7-linux-x64-cflinuxfs3-70a1f47b.tgz"
version = "3.6.7"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "a1aa37d8f08e9de78be4d9bd0efd09837c5ee37d6cef0689787ee4110453f6c6"
source = "https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz"
source_sha256 = "7f5b1f08b3b0a595387ef6c64c85b1b13b38abef0dd871835ee923262e4f32f0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.8-linux-x64-cflinuxfs2-a1aa37d8.tgz"
version = "3.6.8"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "c8a7acb56fd84ad77ab273e0f68af741eae772678878aa09fbfb5af62f4d40dd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.8-linux-x64-cflinuxfs2-c8a7acb5.tgz"
version = "3.6.8"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "83d51734622b46e6c7c5a92e3f757f09451a4959fa295ffeb6e4b1a300011676"
source = "https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz"
source_sha256 = "7f5b1f08b3b0a595387ef6c64c85b1b13b38abef0dd871835ee923262e4f32f0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.8-linux-x64-cflinuxfs3-83d51734.tgz"
version = "3.6.8"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "2b800c6f5d6df8546225035fab66d5e84681d51d94f9b8d2ec3f020a9569ac88"
source = "https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz"
source_sha256 = "f09d83c773b9cc72421abba2c317e4e6e05d919f9bcf34468e192b6a6c8e328d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.2-linux-x64-cflinuxfs3-2b800c6f.tgz"
version = "3.7.2"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "8fad39c254588162e9c46af501da94fa268c34ac89fe31e08fa50c863f28b02e"
source = "https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz"
source_sha256 = "d62e3015f2f89c970ac52343976b406694931742fbde2fed8d1ce8ebb4e1f8ff"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.3-linux-x64-cflinuxfs3-8fad39c2.tgz"
version = "3.7.3"

[[metadata.dependency_deprecation_dates]]
date = 2020-01-01T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0373/"
name = "python"
version_line = "2.7.x"

[[metadata.dependency_deprecation_dates]]
date = 2019-03-16T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0429/"
name = "python"
version_line = "3.4.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-09-13T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0478/"
name = "python"
version_line = "3.5.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-23T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0494/"
name = "python"
version_line = "3.6.x"

[[metadata.dependency_deprecation_dates]]
date = 2023-06-27T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0537/"
name = "python"
version_line = "3.7.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
