api = "0.2"

[buildpack]
id = "org.cloudfoundry.python-runtime"
name = "Python Runtime Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
python = "2.7.*"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "31404cdc49dbe26754b19c01292c520ae14a1781c6e1780cb0ffe9d3e69aed77"
source = "https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz"
source_sha256 = "18617d1f15a380a919d517630a9cd85ce17ea602f9bbdc58ddc672df4b0239db"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.15-linux-x64-cflinuxfs3-31404cdc.tgz"
version = "2.7.15"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "3a775f67c843d53eb8429aafd260a9f908e67671ae2d72d09c77c15dcaf789a1"
source = "https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz"
source_sha256 = "01da813a3600876f03f46db11cc5c408175e99f03af2ba942ef324389a83bad5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.16-linux-x64-cflinuxfs3-3a775f67.tgz"
version = "2.7.16"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "cefa2b44d2b4ce351bc4e19769b17911cd5198729e58d48465790d677999cb21"
source = "https://www.python.org/ftp/python/3.4.9/Python-3.4.9.tgz"
source_sha256 = "e02e565372750a6678efe35ddecbe5ccd5330a8a2e8bbe38d3060713492e3dab"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.9-linux-x64-cflinuxfs3-cefa2b44.tgz"
version = "3.4.9"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "1c06f7a78b3893a5d5c6fb97dfa2cab53c5ac6de6edbae9b7b376f24717ca970"
source = "https://www.python.org/ftp/python/3.4.10/Python-3.4.10.tgz"
source_sha256 = "217757699249ab432571b381386d441e12b433100ab5f908051fcb7cced2539d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.10-linux-x64-cflinuxfs3-1c06f7a7.tgz"
version = "3.4.10"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "e81fac006b856cbd9d293e77fb09204f4c6aa9465ae9b91cdf49514743d025d2"
source = "https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz"
source_sha256 = "30d2ff093988e74283e1abfee823292c6b59590796b9827e95ba4940b27d26f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.6-linux-x64-cflinuxfs3-e81fac00.tgz"
version = "3.5.6"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "81f40b1aa0122846a033fb0c468f8209f5164a75d5549f906b0827d79fa5bfa1"
source = "https://www.python.org/ftp/python/3.5.7/Python-3.5.7.tgz"
source_sha256 = "542d94920a2a06a471a73b51614805ad65366af98145b0369bc374cf248b521b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.7-linux-x64-cflinuxfs3-81f40b1a.tgz"
version = "3.5.7"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "0e8b91a865827da8da86feefc0c43ecdefe6bb0d3456acf6ef61958552540b67"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.8-linux-x64-cflinuxfs3-0e8b91a8.tgz"
version = "3.6.8"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "f30bc832807402a93c24d6984182e00575bde327e2e43f00a0a1c5e680ad53b6"
source = "https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz"
source_sha256 = "47fc92a1dcb946b9ed0abc311d3767b7215c54e655b17fd1d3f9b538195525aa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.9-linux-x64-cflinuxfs3-f30bc832.tgz"
version = "3.6.9"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "827f07e197aead8bd7f2a6387db97b956dd258262108a2ef893a16669682858c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.3-linux-x64-cflinuxfs3-827f07e1.tgz"
version = "3.7.3"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "844697ea88d99a357ed8b4a31f95ba999d73bec5c6b2150cd8c5e8cc120f6992"
source = "https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz"
source_sha256 = "d63e63e14e6d29e17490abbe6f7d17afb3db182dbd801229f14e55f4157c4ba3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.4-linux-x64-cflinuxfs3-844697ea.tgz"
version = "3.7.4"

[[metadata.dependency_deprecation_dates]]
date = 2020-01-01T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0373/"
name = "python"
version_line = "2.7.x"

[[metadata.dependency_deprecation_dates]]
date = 2019-03-16T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0429/"
name = "python"
version_line = "3.4.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-09-13T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0478/"
name = "python"
version_line = "3.5.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-23T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0494/"
name = "python"
version_line = "3.6.x"

[[metadata.dependency_deprecation_dates]]
date = 2023-06-27T00:00:00Z
link = "https://www.python.org/dev/peps/pep-0537/"
name = "python"
version_line = "3.7.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
