
[buildpack]
id = "org.cloudfoundry.buildpacks.python"
name = "Python Buildpack"
version = "0.0.1"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "972402429ca6cd32a0728b7856aed86c6690d6233161d68b36e7709bf4927f01"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.14-linux-x64-cflinuxfs2-97240242.tgz"
version = "2.7.14"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "95f23a26eb66cb2a569e404f0c15c6966f613591031eb5e7f988bd6e3f5b6ab4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.14-linux-x64-cflinuxfs3-95f23a26.tgz"
version = "2.7.14"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "e0dd33dd7487d56a18a9c50a5d7a9a268727ac3b1d50332247a0998d78d5d922"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.15-linux-x64-cflinuxfs2-e0dd33dd.tgz"
version = "2.7.15"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "6325517609c732f44e4279f673c615bcded2d26bde2811f5861f21abcd9a531d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.15-linux-x64-cflinuxfs3-63255176.tgz"
version = "2.7.15"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "905e51c6312b59a16d4e7afdaf8f5567d7ff11ecc31349c229d20479acf379b2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.8-linux-x64-cflinuxfs2-905e51c6.tgz"
version = "3.4.8"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "2554bb9d3ab9934daf37ef02a3422dd13952f4a9f92ba915a46f06048ca56e44"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.8-linux-x64-cflinuxfs3-2554bb9d.tgz"
version = "3.4.8"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "d02592a70bf05f7b04c10550517a716fad028fbdb163c67b8e5505bc7699fd9f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.9-linux-x64-cflinuxfs2-d02592a7.tgz"
version = "3.4.9"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "729999fd87829fb19a1f2d46a2fffa9a4944f3db62f7bd6d157d88ef44c16e93"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.4.9-linux-x64-cflinuxfs3-729999fd.tgz"
version = "3.4.9"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "e1524caeacf64bfba97e8034c108c959a8c7f188e15e11419cc0bd83e53f56f2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.5-linux-x64-cflinuxfs2-e1524cae.tgz"
version = "3.5.5"

[[metadata.dependencies]]
id = "python"
name = "Python"
sha256 = "0d1517b8d13750a0222e63ebcd92a09c4ae2e5739b728179d967ee66ae031fae"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.5-linux-x64-cflinuxfs3-0d1517b8.tgz"
version = "3.5.5"

[[metadata.dependencies]]
id = "python"
sha256 = "e482c9f43ca07f924f064e4e013aea5cadc235892cd54bee67efa5d4ac1f00ec"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.6-linux-x64-cflinuxfs2-e482c9f4.tgz"
version = "3.5.6"

[[metadata.dependencies]]
id = "python"
sha256 = "2e41cb573659350bd8a90148b89ce7edf72595e1086798394f9646fea2244d95"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.6-linux-x64-cflinuxfs3-2e41cb57.tgz"
version = "3.5.6"

[[metadata.dependencies]]
id = "python"
sha256 = "2ef997d110c14e5cba3be0d229ee8caa963268027b915c3f427d1cf3dd4f5994"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.7-linux-x64-cflinuxfs2-2ef997d1.tgz"
version = "3.6.7"

[[metadata.dependencies]]
id = "python"
sha256 = "70a1f47b1d7eccd0068cc1670ee3b29f92d02f847308ceb0e9027a3e4f8a7b94"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.7-linux-x64-cflinuxfs3-70a1f47b.tgz"
version = "3.6.7"

[[metadata.dependencies]]
id = "python"
sha256 = "c8a7acb56fd84ad77ab273e0f68af741eae772678878aa09fbfb5af62f4d40dd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.8-linux-x64-cflinuxfs2-c8a7acb5.tgz"
version = "3.6.8"

[[metadata.dependencies]]
id = "python"
sha256 = "0e8b91a865827da8da86feefc0c43ecdefe6bb0d3456acf6ef61958552540b67"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.8-linux-x64-cflinuxfs3-0e8b91a8.tgz"
version = "3.6.8"

[[metadata.dependencies]]
id = "python"
sha256 = "edf7ca11af715a63e93ce589b5ae20a2a2c975a7d62d89ebd613f7583b56ed19"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.1-linux-x64-cflinuxfs3-edf7ca11.tgz"
version = "3.7.1"

[[metadata.dependencies]]
id = "python"
sha256 = "2b800c6f5d6df8546225035fab66d5e84681d51d94f9b8d2ec3f020a9569ac88"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.2-linux-x64-cflinuxfs3-2b800c6f.tgz"
version = "3.7.2"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"
